### ISSUE TITLE
Installation Manual

### ISSUE THREAD

**Issue by jjmwiwi** [welles/DoxieServer#1]
Dear Nico,

I suppose this Project is exactly what I need: pulling automatically documents from my Doxie Q. 

Unfortunately I cannot find an installation manual. 

How do I install it with docker? is there any docker compose file?

Thanks

**Comment by welles** [comment]
Hi, sorry about that, I didn't expect anyone to actually use this! 😅
I was meaning to write a proper README and docker-compose example but never got around to it.
I will see if I can get to it in the next few days.

**Comment by jjmwiwi** [comment]
Hi
Yes indeed. I will definitely use it!
My idea is to pull documents automatically out from my Doxie an sync it with my paperless ngx consume folder.

Would be fantastic if this works! A docker compose file example would help a lot incl. some comments! 

Highly appreciated

**Comment by jjmwiwi** [comment]
Dear Nico,

I assume you didnt find the time to work on this. I am using Paperless NgX with my Doxie Q and I assume that this will really help me a lot to prevent a lot of manual steps.

Thanks a lot for your help

Jürgen

**Comment by welles** [comment]
Hi, sorry for the wait! The documentation is now up!

**Comment by jjmwiwi** [comment]
Oh wow, what a great documentation!!!!

Thanks so much! Really appreciated
