### ISSUE TITLE
Raspberry Pi4

### ISSUE THREAD

**Issue by jjmwiwi** [welles/DoxieServer#2]
Dear Welles,

i am trying to run your DoxieServer with Docker on a RapsberryPi4. Unfortunately, the docker compose up creates the following error code:

pdoxie-doxieserver-1 exited with code 1
 ! doxieserver The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v8) and no sp

Any hints to overcome this?

Thanks a lot

**Comment by welles** [comment]
Hi, I think I will need to build a Docker image for linux/arm64. Give me a few days, I will check how to do that and get back to you

**Comment by welles** [comment]
Well that was, a quick google search and rebuild/push seemed to have added support for ARM64. Please try running the image again on your Pi and let me know if it works

**Comment by welles** [comment]
I'm going to assume that it worked, feel free to reopen the issue if there are any problems.
